
import JSZip from 'jszip';

const iconSizes = {
  android: [
    { name: 'ic_launcher.png', size: 48, folder: 'android/mipmap-mdpi' },
    { name: 'ic_launcher.png', size: 72, folder: 'android/mipmap-hdpi' },
    { name: 'ic_launcher.png', size: 96, folder: 'android/mipmap-xhdpi' },
    { name: 'ic_launcher.png', size: 144, folder: 'android/mipmap-xxhdpi' },
    { name: 'ic_launcher.png', size: 192, folder: 'android/mipmap-xxxhdpi' },
  ],
  ios: [
    { name: 'Icon-20.png', size: 20, folder: 'ios' },
    { name: 'Icon-29.png', size: 29, folder: 'ios' },
    { name: 'Icon-40.png', size: 40, folder: 'ios' },
    { name: 'Icon-58.png', size: 58, folder: 'ios' },
    { name: 'Icon-60.png', size: 60, folder: 'ios' },
    { name: 'Icon-76.png', size: 76, folder: 'ios' },
    { name: 'Icon-80.png', size: 80, folder: 'ios' },
    { name: 'Icon-87.png', size: 87, folder: 'ios' },
    { name: 'Icon-120.png', size: 120, folder: 'ios' },
    { name: 'Icon-152.png', size: 152, folder: 'ios' },
    { name: 'Icon-167.png', size: 167, folder: 'ios' },
    { name: 'Icon-180.png', size: 180, folder: 'ios' },
    { name: 'Icon-512.png', size: 512, folder: 'ios' },
    { name: 'Icon-1024.png', size: 1024, folder: 'ios' },
  ],
  macos: [
    { name: 'icon_16x16.png', size: 16, folder: 'macos' },
    { name: 'icon_32x32.png', size: 32, folder: 'macos' },
    { name: 'icon_64x64.png', size: 64, folder: 'macos' },
    { name: 'icon_128x128.png', size: 128, folder: 'macos' },
    { name: 'icon_256x256.png', size: 256, folder: 'macos' },
    { name: 'icon_512x512.png', size: 512, folder: 'macos' },
    { name: 'icon_1024x1024.png', size: 1024, folder: 'macos' },
  ],
};

export const createIconsZip = async (icons: { [key: string]: string }): Promise<Blob> => {
  const zip = new JSZip();

  // Add Android icons
  iconSizes.android.forEach(({ name, size, folder }) => {
    const iconData = icons[`android-${size}`];
    if (iconData) {
      const base64Data = iconData.split(',')[1];
      zip.file(`${folder}/${name}`, base64Data, { base64: true });
    }
  });

  // Add iOS icons
  iconSizes.ios.forEach(({ name, size, folder }) => {
    const iconData = icons[`ios-${size}`];
    if (iconData) {
      const base64Data = iconData.split(',')[1];
      zip.file(`${folder}/${name}`, base64Data, { base64: true });
    }
  });

  // Add macOS icons
  iconSizes.macos.forEach(({ name, size, folder }) => {
    const iconData = icons[`macos-${size}`];
    if (iconData) {
      const base64Data = iconData.split(',')[1];
      zip.file(`${folder}/${name}`, base64Data, { base64: true });
    }
  });

  // Add README file
  const readmeContent = `# App Icons Generated

This package contains app icons for multiple platforms:

## Android Icons (/android/)
- Located in mipmap folders (mdpi, hdpi, xhdpi, xxhdpi, xxxhdpi)
- All named ic_launcher.png
- Ready to use in Android projects

## iOS Icons (/ios/)
- Various sizes from 20px to 1024px
- Includes all required sizes for iPhone, iPad, and App Store
- Follow Apple's naming conventions

## macOS Icons (/macos/)
- Sizes from 16px to 1024px
- Standard naming convention for Mac applications
- Ready for .icns conversion

Generated by App Icon Generator
`;

  zip.file('README.md', readmeContent);

  return await zip.generateAsync({ type: 'blob' });
};
